import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Metadata } from "next";
import PageTransition from "@/components/PageTransition";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="transition-colors duration-300">
      <body className="font-sans antialiased text-gray-900 transition-colors duration-300 bg-white bg-gray-50 dark:text-gray-100 dark:bg-gray-800">
        <Header />
        <main className="max-w-5xl px-6 py-16 mx-auto">
          <PageTransition>
            {children}
          </PageTransition>
        </main>
        <Footer />
      </body>
    </html>
  );
}
